apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-hello-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: go
  endpoints:
  - port: web
    path: /metrics
    interval: 15s