apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kube-hello-blue
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-hello-blue
            port:
              number: 9376
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kube-hello-green
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "30"
spec:
  rules:
  - host: hello.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-hello-green
            port:
              number: 9376